ShopBanHoa/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopBanHoa.Models;

namespace ShopBanHoa.Controllers
{
    public class AboutController : Controller
    {
        FlowEntities db = new FlowEntities();

        // GET: About
        public ActionResult Index()
        {

            return View();

        }
        public ActionResult Getgioithieu()
        {
            var v = from t in db.Gioithieux
                    where t.hide == true
                    orderby t.order ascending
                    select t;
            return PartialView(v.ToList());
        }
    }
}

ShopBanHoa/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopBanHoa.Models;

namespace ShopBanHoa.Controllers
{
    public class HomeController : Controller
    {
        FlowEntities db = new FlowEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult getMenu()
        {
            var v = from t in db.menus
                    where t.hide == true
                    select t;
            return PartialView(v.ToList());
        }

        public ActionResult getBanner()
        {
            var v = from t in db.banners
                    where t.hide == true
                    select t;
            return PartialView(v.ToList());
        }

        public ActionResult getborder()
        {
            var v = from t in db.products
                    where t.hide == true && t.categoryid == 50
                    select t;
            return PartialView(v.ToList());
        }
        
        public ActionResult getCH()
        {
            var v = from t in db.CuaHangs select t;
            return PartialView(v.ToList());
        }

        public ActionResult getCNhanh()
        {
            var v = from t in db.Categories
                    where t.hide == true && t.CN==true
                    select t;
            return PartialView(v.ToList());
        }
    }
}

ShopBanHoa/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopBanHoa.Models;

namespace ShopBanHoa.Controllers
{
    public class SanPhamController : Controller
    {
        FlowEntities db = new FlowEntities();
        // GET: SanPham
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult getProduct()
        {
            ViewBag.meta = "san-pham";
            var v = from t in db.products
                    where t.hide == true && t.categoryid != 50
                    select t;
            return PartialView(v.ToList());
        }

        public ActionResult getProductHoaCuoi(int? id, string metatitle)
        {
            ViewBag.meta = metatitle;
            var v = from t in db.products
                    where t.hide == true && t.categoryid == 1
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getProductHoaTotNghiep()
        {
            var v = from t in db.products
                    where t.hide == true && t.categoryid == 2
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getProductHoaSN()
        {
            var v = from t in db.products
                    where t.hide == true && t.categoryid == 3
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getProductHoaThangChuc()
        {
            var v = from t in db.products
                    where t.hide == true && t.categoryid == 4
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getProductHoaKhaiTruong()
        {
            var v = from t in db.products
                    where t.hide == true && t.categoryid == 5
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getProductHoaVieng()
        {
            var v = from t in db.products
                    where t.hide == true && t.categoryid == 6
                    select t;
            return PartialView(v.ToList());
        }

        public ActionResult Detail(long id)
        {
            var v = from t in db.products
                    where t.id == id
                    select t;
            return View(v.FirstOrDefault());
        }
        public ActionResult GetChooseProduct()
        {
            var v = from t in db.Choose_products
                    where t.hide == true 
                    select t;
            return PartialView(v.FirstOrDefault());
        }

    }
}

ShopBanHoa/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ShopBanHoa/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ShopBanHoa/Views/Home/Index.cshtml
<!-- start slider -->
<!-- Bootstrap Core CSS -->
<div id="fwslider" style="height: 485px;">
    <div class="slider_container">
        @{Html.RenderAction("getBanner", "Home");}
    </div>
    <div class="timers" style="width: 135px;"><div class="timer"><div class="progress" style="width: 100%; overflow: hidden;"></div></div><div class="timer"><div class="progress" style="overflow: hidden; width: 12.44%;"></div></div></div>
    <div class="slidePrev" style="left: 0px; top: 207.5px;"><span></span></div>
    <div class="slideNext" style="right: 0px; top: 207.5px; opacity: 0.5;"><span></span></div>
</div>
<!--/slider -->
<div class="main">
    <div class="wrap">
        <div class="section group">
            <div class="cont span_2_of_3">
                <h2 class="head">Hoa cưới</h2>
                <div class="top-box1">
                    @{ Html.RenderAction("getProductHoaCuoi", "SanPham");}
                    <div class="clear"></div>
                </div>
                <h2 class="head">Hoa tốt nghiệp</h2>
                <div class="top-box1">
                    @{ Html.RenderAction("getProductHoaTotNghiep", "SanPham");}
                    <div class="clear"></div>
                </div>
                <h2 class="head">Hoa sinh nhật</h2>
                <div class="top-box1">
                    @{ Html.RenderAction("getProductHoaSN", "SanPham");}
                    <div class="clear"></div>
                </div>
                <h2 class="head">Hoa khai trương</h2>
                <div class="top-box1">
                    @{ Html.RenderAction("getProductHoaKhaiTruong", "SanPham");}
                    <div class="clear"></div>
                </div>
                <h2 class="head">Hoa thăng chức</h2>
                <div class="top-box1">
                    @{ Html.RenderAction("getProductHoaThangChuc", "SanPham");}
                    <div class="clear"></div>
                </div>
                <h2 class="head">Hoa viếng</h2>
                <div class="top-box1">
                    @{ Html.RenderAction("getProductHoaVieng", "SanPham");}
                    <div class="clear"></div>
                </div>
            </div>
            <div class="rsidebar span_1_of_left">
                <div class="top-border"> </div>
                <div class="border">
                    <link href="~/Content/css/default.css" rel="stylesheet" type="text/css" media="all" />
                    <link href="~/Content/css/nivo-slider.css" rel="stylesheet" type="text/css" media="all" />
                    <script src="~/Content/js/jquery.nivo.slider.js"></script>
                    <script type="text/javascript">
                        $(window).load(function () {
                            $('#slider').nivoSlider();
                        });
                    </script>
                    <div class="slider-wrapper theme-default">
                        <div id="slider" class="nivoSlider">
                            @{ Html.RenderAction("getborder", "Home");}
                        </div>
                    </div>
                    <div class="btn"><a href="single.html">Check it Out</a></div>
                </div>
                <div class="top-border"> </div>
                <div class="sidebar-bottom" style="background-color: red; border-radius: 10px; color: white; font-weight: bold">Tin mới</div>
                <div class="sidebar-bottom">
                    @{ Html.RenderAction("getnew", "new");}
                    <hr />
                    <div class="subscribe">
                        <form>
                            <input name="userName" type="text" class="textbox" placeholder="Nhập nội dung cần tìm">
                            <input type="submit" value="Tìm kiếm">
                        </form>
                    </div>
                </div>
                <iframe width="243" height="145" src="https://www.youtube.com/embed/epGzL7dr0C0?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

ShopBanHoa/Views/Home/getBanner.cshtml
@model IEnumerable<ShopBanHoa.Models.banner>

@foreach (var i in Model)
{
    <div class="slide" style="display: none; z-index: 0; opacity: 1;">
        <img src="~/Content/update/banner/@i.image" alt="">
        <div class="slide_content">
            <div class="slide_content_wrap">
                <h4 class="title" style="opacity: 0;">@i.title1</h4>
                <p class="description" style="opacity: 0;">@i.title2</p>
            </div>
        </div>
    </div>
}

ShopBanHoa/Views/Home/getCH.cshtml
@model IEnumerable<ShopBanHoa.Models.CuaHang>

@foreach (var i in Model)
{
    <div class="col_1_of_f_2 span_1_of_f_2">
        <h3>Thông Tin LIên Hệ</h3>
        <div class="company_address">
            <p>@i.TenCH</p>
            <p>@i.DiaChi</p>
            <p>USA</p>
            <p>@i.SDT</p>
            <p>Fax: (000) 000 00 00 0</p>
            <p>Email: <span>mail[at]leoshop.com</span></p>

        </div>
        
    </div>
}

ShopBanHoa/Views/Home/getCNhanh.cshtml
@model IEnumerable<ShopBanHoa.Models.Category>

@foreach (var i in Model)
{
    <ul class="f-list1">
        <li><a href="#">@i.name </a></li>

    </ul>
}
<li><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1307.8505995406033!2d106.71436052773808!3d10.801847213585102!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528a459cb43ab%3A0x6c3d29d370b52a7e!2sHUTECH+University!5e0!3m2!1sen!2s!4v1524045015374" width="265" height="200" frameborder="0" style="border:0" allowfullscreen></iframe></li>

ShopBanHoa/Views/Home/getMenu.cshtml
@model IEnumerable<ShopBanHoa.Models.menu>

@foreach(var i in Model)
{
    <li class="active grid"><a href="@ViewBag.meta/@i.meta">@i.title</a></li>
}

ShopBanHoa/Views/Home/getborder.cshtml
@model IEnumerable<ShopBanHoa.Models.product>

@foreach (var i in Model)
{
    <img src="~/Content/update/product/@i.img" alt="" />
}