ShopBanHoa/Models/banner.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public int id { get; set; }
        public string image { get; set; }
        public string title1 { get; set; }
        public string title2 { get; set; }
        public string link { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    }
}

ShopBanHoa/Areas/admin/Controllers/bannersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopBanHoa.Models;

namespace ShopBanHoa.Areas.admin.Controllers
{
    public class bannersController : Controller
    {
        private FlowEntities db = new FlowEntities();

        // GET: admin/banners
        public ActionResult Index()
        {
            return View(db.banners.ToList());
        }

        // GET: admin/banners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            banner banner = db.banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // GET: admin/banners/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/banners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,image,title1,title2,link,meta,hide,order,datebegin")] banner banner)
        {
            if (ModelState.IsValid)
            {
                db.banners.Add(banner);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(banner);
        }

        // GET: admin/banners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            banner banner = db.banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // POST: admin/banners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,image,title1,title2,link,meta,hide,order,datebegin")] banner banner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(banner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(banner);
        }

        // GET: admin/banners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            banner banner = db.banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // POST: admin/banners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            banner banner = db.banners.Find(id);
            db.banners.Remove(banner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopBanHoa/Areas/admin/Controllers/newsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopBanHoa.Models;

namespace ShopBanHoa.Areas.admin.Controllers
{
    public class newsController : Controller
    {
        private FlowEntities db = new FlowEntities();

        // GET: admin/news
        public ActionResult Index()
        {
            return View(db.news.ToList());
        }

        // GET: admin/news/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: admin/news/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/news/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,img,description,detail,meta,hide,order,datebegin,price,img1,img2,description1,description2,nguon")] news news)
        {
            if (ModelState.IsValid)
            {
                db.news.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(news);
        }

        // GET: admin/news/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: admin/news/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,img,description,detail,meta,hide,order,datebegin,price,img1,img2,description1,description2,nguon")] news news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: admin/news/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: admin/news/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            news news = db.news.Find(id);
            db.news.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopBanHoa/Areas/admin/Views/banners/Create.cshtml
@model ShopBanHoa.Models.banner

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

<h2>Thêm Mới</h2>

@using (Html.BeginForm("Create", "news", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BANNER</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="img" id="img" accept=".jpg,.png,.gif,.jpeg,.bmp" />
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tiêu Đề", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.title1)
                @Html.ValidationMessageFor(model => model.title1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tiêu Đề Phụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.title2)
                @Html.ValidationMessageFor(model => model.title2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Link", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Meta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.meta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ẩn / Hiện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @{
                        bool hide = true;
                    }
                    @Html.CheckBoxFor(model => hide, new { Style = "margin : -1px 5px" })
                    @Html.ValidationMessageFor(model => model.hide, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("STT hiển thị", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.order, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.order, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ngày", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datebegin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datebegin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm Mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay Lại", "Index")
</div>
@section _Footer
{
    <!-- DataTables JavaScript -->

    <script src="~/Areas/admin/Content/ckfinder/ckfinder/ckfinder.js"></script>">
    <script src="~/Areas/admin/Content/ckeditor/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">

        var editor = CKEDITOR.replace("title1");
        var editor = CKEDITOR.replace("title1", { height: '600px' });
       

        customConfig: '/Areas/admin/Content/ckeditor/ckeditor/config.js';

    </script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
        $(function () {
            $("#name").keyup(function () {
                var text = $.trim($(this).val().toLocaleLowerCase());
                var text_create;
                text_create = text.replace(/à|á|ạ|ả|ã|ấ|ầ|ẫ|ă|ằ|ắ|ẵ/g, "a").replace(/\ /g, '_').replace(/đ/g, "d"
                                            $('#meta').val(text_create);)

        }).keyup();
                                    });
    </script>

        <!-- DataTables JavaScript -->

        <script src="~/Areas/admin/Content/ckfinder/ckfinder/ckfinder.js"></script>">
        <script src="~/Areas/admin/Content/ckeditor/ckeditor/ckeditor.js"></script>
        <script type="text/javascript">

          
            var editor = CKEDITOR.replace("title2");
            var editor = CKEDITOR.replace("title2", { height: '600px' });

            customConfig: '/Areas/admin/Content/ckeditor/ckeditor/config.js';

        </script>
        <!-- Page-Level Demo Scripts - Tables - Use for reference -->
        <script>
            $(document).ready(function () {
                $('#dataTables-example').DataTable({
                    responsive: true
                });
            });
            $(function () {
                $("#name").keyup(function () {
                    var text = $.trim($(this).val().toLocaleLowerCase());
                    var text_create;
                    text_create = text.replace(/à|á|ạ|ả|ã|ấ|ầ|ẫ|ă|ằ|ắ|ẵ/g, "a").replace(/\ /g, '_').replace(/đ/g, "d"
                                                $('#meta').val(text_create);)

            }).keyup();
                                        });
        </script>
   
}

ShopBanHoa/Areas/admin/Views/banners/Delete.cshtml
@model ShopBanHoa.Models.banner

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>banner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.meta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hide)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hide)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datebegin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datebegin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShopBanHoa/Areas/admin/Views/banners/Details.cshtml
@model ShopBanHoa.Models.banner

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>banner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.meta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hide)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hide)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datebegin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datebegin)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShopBanHoa/Areas/admin/Views/banners/Edit.cshtml
@model ShopBanHoa.Models.banner

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>banner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.link, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.meta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.meta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hide, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.hide)
                    @Html.ValidationMessageFor(model => model.hide, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.order, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.order, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datebegin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datebegin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datebegin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShopBanHoa/Areas/admin/Views/banners/Index.cshtml
@model IEnumerable<ShopBanHoa.Models.banner>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_MyLayout.cshtml";
}
@section _Header
{
    <!-- DataTables CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Quản lý Banner
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <p>

                    @Html.ActionLink("Thêm mới", "Create", "Create", new { @class = "btn btn-success" })
                </p>
                <table class="table table-striped table-bordered table-hover" id="dataTables-example" style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                STT
                            </th>
                            <th>
                                HÌNH 
                            </th>
                            <th>
                                TIÊU ĐỀ
                            </th>
                            <th>
                                TIÊU ĐỀ PHỤ
                            </th>
                            <th>
                                ẨN/HIỆN
                            </th>
                            <th> CHỨC NĂNG</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ var Number = 1;  }
                        @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.Raw(Number++)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.image)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.title1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.title2)
                    </td>
                    <td>
                        @(item.hide.GetValueOrDefault(false) ? "Hiển Thị" : "Ẩn")
                    </td>
                    <td>
                        @Html.ActionLink("Sửa ", "Edit", new { id = item.id }, new { @class = " fa fa-edit" }) |
                        @Html.ActionLink("Chi Tiết", "Details", new { id = item.id }, new { @class = " fa fa-info-circle" }) |
                        @Html.ActionLink("Xóa", "Delete", new { id = item.id }, new { @class = " fa fa-times    " })
                    </td>
                </tr>
}
                    </tbody>
                </table>
                @section _Footer
{
                    <!-- DataTables JavaScript -->
                    <script src="/Areas/admin/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
                    <script src="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
                    <script src="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
                    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
                    <script>
                        $(document).ready(function () {
                            $('#dataTables-example').DataTable({
                                responsive: true
                            });
                        });
                    </script>
                }